schedule_study_reminder_task:
  description: >
    Schedule a proactive study reminder for the user using Google Calendar and Twilio.
    Create calendar events for study sessions and send SMS/WhatsApp notifications to keep 
    the user engaged with their learning journey.
    
    Input parameters:
    - user_email: User's email for calendar events
    - phone_number: User's phone number for SMS/WhatsApp
    - subject: Subject/topic for the study session
    - reminder_time: When to send the reminder
    - preferences: User's notification preferences
    
    Use Google Calendar to schedule the study session and Twilio to send immediate 
    notifications. Ensure the timing is personalized based on user preferences.
  expected_output: >
    A JSON object confirming the reminder was scheduled:
    {
      "success": true,
      "calendar_event": {
        "event_id": "calendar_event_id",
        "event_link": "google_calendar_link",
        "scheduled_time": "ISO_datetime"
      },
      "notification": {
        "type": "sms_or_whatsapp",
        "status": "sent_or_scheduled",
        "message_id": "twilio_message_id"
      },
      "message": "Study reminder scheduled successfully"
    }
  agent: notification_agent
  output_file: "data/reminder_scheduled.json"

send_achievement_notification_task:
  description: >
    Send achievement notifications to celebrate user milestones and maintain motivation.
    Use Twilio to send personalized SMS or WhatsApp messages celebrating achievements,
    badges earned, or learning milestones.
    
    Input parameters:
    - user_name: User's name for personalization
    - phone_number: User's phone number
    - achievement: Description of the achievement
    - badge_name: Name of the badge earned (if applicable)
    - method: "sms" or "whatsapp"
    
    Create engaging, motivational messages that celebrate the user's progress and 
    encourage continued learning. Use emojis and positive language to maintain 
    enthusiasm for learning.
  expected_output: >
    A JSON object confirming the notification was sent:
    {
      "success": true,
      "notification": {
        "type": "achievement_alert",
        "method": "sms_or_whatsapp",
        "message_sid": "twilio_message_id",
        "status": "delivered_or_sent"
      },
      "message": "Achievement notification sent successfully"
    }
  agent: notification_agent
  output_file: "data/notification_sent.json"